version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  run_flask:
    docker:
      -image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Installing Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
        - run:
          name: Run unit tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
        - store_test_results:
            path: test-reports
        - store_artifacts:
            path: test-reports
workflows:
  build_flask:
    jobs:
      - run_flask